name: Auto Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Extract Version from module.json
        id: get_version
        run: |
          # Using jq to parse the version field from module.json at repo root
          VERSION=$(jq -r '.version' module.json)
          echo "Found version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "::set-output name=version::$VERSION"

      - name: Extract Changelog Entry
        id: get_changelog
        run: |
          # Extract changelog entry for current version
          VERSION="${{ env.VERSION }}"
          # Use awk to extract the section between ## [$VERSION] and the next ## or end of file
          CHANGELOG=$(awk -v ver="$VERSION" '
            BEGIN { printing = 0; entry = ""; }
            /^## \['"$VERSION"'\]/ { printing = 1; next; }
            /^## \[/ { if (printing) { printing = 0; } }
            { if (printing) entry = entry $0 "\n"; }
            END { printf "%s", entry; }
          ' CHANGELOG.md)
          # Store changelog in output, escaping newlines for GitHub Actions
          echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Create Git Tag
        id: tag
        run: |
          TAG="v${{ env.VERSION }}"
          echo "Creating tag: $TAG"
          git tag "$TAG"
          git push origin "$TAG"
          echo "::set-output name=tag::$TAG"

      - name: Create Module ZIP
        run: |
          # Zip everything in the repo except hidden folders/files we don't need
          zip -r bg3-inspired-hotbar.zip . \
            -x "*.git*" \
               ".github*" \
               "*.vscode*"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          name: Release ${{ steps.tag.outputs.tag }}
          body: ${{ steps.get_changelog.outputs.CHANGELOG }}
          files: |
            bg3-inspired-hotbar.zip
            module.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
