name: Update FoundryVTT Package

on:
  release:
    types: [published]

jobs:
  update-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update Foundry Package on FoundryVTT
        run: |
          # Set variables from GitHub release data and repository details
          PACKAGE_ID="${{ secrets.FOUNDRY_PACKAGE_ID }}"
          API_URL="https://api.foundryvtt.com/_api/packages/release_version/"
          VERSION="${{ github.event.release.tag_name }}"
          MANIFEST_URL="https://github.com/BragginRites/bg3-inspired-hotbar/releases/download/${VERSION}/module.json"
          NOTES_URL="https://github.com/BragginRites/bg3-inspired-hotbar/releases/tag/${VERSION}"
          
          # Define compatibility details (update these as appropriate for your module)
          MIN_COMPAT="12"
          VERIFIED_COMPAT="12"
          MAX_COMPAT="12"

          # Build the JSON payload using jq
          JSON_PAYLOAD=$(jq -n \
            --arg id "$PACKAGE_ID" \
            --arg version "$VERSION" \
            --arg manifest "$MANIFEST_URL" \
            --arg notes "$NOTES_URL" \
            --arg min "$MIN_COMPAT" \
            --arg verified "$VERIFIED_COMPAT" \
            --arg max "$MAX_COMPAT" \
            '{
              id: $id,
              "dry-run": false,
              release: {
                version: $version,
                manifest: $manifest,
                notes: $notes,
                compatibility: {
                  minimum: $min,
                  verified: $verified,
                  maximum: $max
                }
              }
            }')

          echo "JSON Payload: $JSON_PAYLOAD"

          # Post the payload to the Foundry API
          curl -X POST "$API_URL" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.FOUNDRY_API_KEY }}" \
            -d "$JSON_PAYLOAD"
        env:
          FOUNDRY_API_KEY: ${{ secrets.FOUNDRY_API_KEY }}
          FOUNDRY_PACKAGE_ID: ${{ secrets.FOUNDRY_PACKAGE_ID }}
